# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - MyMSIFunctionApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://msipoc.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e38a74f42e704b9590881466bbbae817 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bc44ef30f38a4391a55c185fd8de316b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: msipoc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e38a74f42e704b9590881466bbbae817 }}/test-msi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MyMSIFunctionApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dd96ffc167ec491089fbcca80dc2a6b7 }}
        images: 'msipoc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e38a74f42e704b9590881466bbbae817 }}/test-msi:${{ github.sha }}'